- CHANGELOG.md
- lib/openapi_parser/request_operation.rb
- lib/openapi_parser/schemas/operation.rb
- lib/openapi_parser/schemas/responses.rb
- spec/data/petstore-expanded.yaml
- spec/openapi_parser/schemas/responses_spec.rb
OpenAPI3 allow 4XX status code, when we check 404 status code and not exist in definition, we can use 4XX definition.  
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#patterned-fields-1
> support wildcard status code

- lib/openapi_parser/concerns/parameter_validatable.rb
- lib/openapi_parser/parameter_validator.rb
- spec/openapi_parser/schema_validator_spec.rb
Header names are case-insensitive in RFC.
> 3.2.  Header Fields
>    Each header field consists of a case-insensitive field name followed
>    by a colon (":"), optional leading whitespace, the field value, and
>    optional trailing whitespace.
> 
> https://tools.ietf.org/html/rfc7230#section-3.2
bugfix for this PR.
https://github.com/ota42y/openapi_parser/issues/22
> validate_header_parameter support case incentive

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validator.rb
- lib/openapi_parser/schema_validators/one_of_validator.rb
- spec/data/normal.yml
- spec/openapi_parser/schema_validator_spec.rb
Implement `oneOf` schema validator.
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#oneof
> Support one of validator

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validators/any_of_validator.rb
- lib/openapi_parser/schema_validators/base.rb
- lib/openapi_parser/schema_validators/one_of_validator.rb
- lib/openapi_parser/schemas.rb
- lib/openapi_parser/schemas/classes.rb
- lib/openapi_parser/schemas/discriminator.rb
- lib/openapi_parser/schemas/schema.rb
- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schemas/discriminator_spec.rb
- spec/spec_helper.rb
Discriminator option is supported for oneOf and anyOf. Only
discriminator with mapping defined is supported now.
Openapi docs for discriminator and mapping:
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/
TODOs:
> Add support for discriminator

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validator.rb
- lib/openapi_parser/schema_validators/all_of_validator.rb
- lib/openapi_parser/schema_validators/any_of_validator.rb
- lib/openapi_parser/schema_validators/base.rb
- lib/openapi_parser/schema_validators/nil_validator.rb
- lib/openapi_parser/schema_validators/object_validator.rb
- lib/openapi_parser/schema_validators/one_of_validator.rb
- lib/openapi_parser/schemas/base.rb
- spec/data/petstore-expanded.yaml
- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schema_validator/object_validator_spec.rb
- spec/openapi_parser/schema_validator_spec.rb
- spec/openapi_parser/schemas/discriminator_spec.rb
Perform a strict check on properties
We need to throw a validation error if property being send is
not defined. If additionalProperties are defined, we skip the
validation for now, with TODO added.
In a case of composing schema using allOf, the property needs
to be defined at least in 1 of te allOf items, as stated in:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof
Depends on:
> Perform a strict check on object properties

- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schema_validator/all_of_validator_spec.rb
Especially for skipping when nested object has additionalProperties
or doing unknown property validation.
> Add more specs for all_of validation

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validators/base.rb
- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schemas/discriminator_spec.rb
When schema includes a discriminator without mapping, validation raises following error.
```
Failure/Error: mapping_target = discriminator.mapping[mapping_key]
NoMethodError:
undefined method `[]' for nil:NilClass
```
[OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject) is not clear about implicit mapping resolution and I just use `"#/components/schemas/#{key}"`, but it might be better to choose `$ref` from `oneOf`, `anyOf` or `allOf` list.
> Support discriminator without mapping

- CHANGELOG.md
- lib/openapi_parser/concerns/schema_loader/creator.rb
- lib/openapi_parser/schemas/schema.rb
- lib/openapi_parser/version.rb
- spec/data/normal.yml
- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schema_validator/object_validator_spec.rb
We set defalut value as true.
```
Consistent with JSON Schema, additionalProperties defaults to true.
```
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema-object
6f7b39a
> add additionalProperties default value

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validator.rb
- lib/openapi_parser/schema_validators/float_validator.rb
- lib/openapi_parser/schema_validators/integer_validator.rb
- lib/openapi_parser/schema_validators/minimum_maximum.rb
- spec/openapi_parser/schema_validator/integer_validator_spec.rb
This feature is to implement a simple check for `mininum`, `maximum` and also the `exclusiveMinimum` and `exclusiveMaximum` values for integer and number data type.
I added 4 specific Error classes for granularity.
> Add minimum and maximum checks for `integer` and `number` data types

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validators/string_validator.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
closes #50 
I added a simple email format validation for openAPI string types
> add email format validation on string

- lib/openapi_parser/schema_validators/string_validator.rb
match? method is good performance but it added ruby 2.4.
So we don't use ruby 2.3.
When we drop ruby 2.3 support, we should fix it
https://github.com/ota42y/openapi_parser/issues/52
> use match method

- lib/openapi_parser/schemas/response.rb
- spec/data/petstore-expanded.yaml
- spec/openapi_parser/request_operation_spec.rb
As per OpenAPI documentation, the [HeaderObject](https://swagger.io/specification/#headerObject)  follows the structure of the [Parameter Object ](https://swagger.io/specification/#parameterObject), that can specify the property `required`.
This PR adds the validation for the case when `header.schema.required = true` and the actual `header.value == nil`
The current response headers validation skips the validation when the header.value is `nil`, when actually should skip when the header is not present.
> Bugfix: validate non-nullable response header

- lib/openapi_parser/schema_validators/object_validator.rb
- spec/openapi_parser/schema_validator/object_validator_spec.rb
The Schema Object of OpenAPI is derived from JSON Schema Specification Wright Draft 00, and `required` property has the same specification.
The specification says:
> 5.15.  required
>
>   The value of this keyword MUST be an array.  This array MUST have at
least one element.  Elements of this array MUST be strings, and MUST
be unique.
>
>   An object instance is valid against this keyword if its property set
contains all elements in this keyword's array value.
It means `required` property should be checked whether `schema.properties` exists or not.
This PR fixes it.
I wrote a spec of it in a different way.
The reason why I did is
* It seems too difficult to add extra schema to existing fixtures
* It seems not a good idea to test validator through request_operation_object
So I test …
> fix object validator in case of properties missing

- lib/openapi_parser/schemas/path_item.rb
- spec/openapi_parser/path_item_finder_spec.rb
Hi! I've been looking into OpenAPI for a new project and that led me to your project, which seems to be the leading parser in Ruby 🍻 Thanks for your work on it! 
I was just skimming the source and I noticed a place where `.send` was used with dynamic input. It seems like, depending on _where_ that input comes from, it could potentially be used to exit the Ruby process. 
I'd hate to open this up to external traffic, then have someone figure out a way to activate that codepath. It looks to me like `.public_send` would work just as well here, what do you think of changing it, just to make it _impossible_ that it would `exit`? 
(It looks like there are some other calls to `.send`, if you like this change and want to maintain consistency, I'd be happy to change those too. But it looks to me …
> Avoid potential `.send(:exit)`

- lib/openapi_parser/path_item_finder.rb
- spec/data/petstore-expanded.yaml
- spec/openapi_parser/path_item_finder_spec.rb
I've discovered the edge case when the path and params are matched incorrectly even if the matched path doesn't contain searched HTTP method at all and path has completely different length. I've added the spec that proofs existence of the bug:
`spec/openapi_parser/path_item_finder_spec.rb`
I've rewritten `PathItemFinder` to fix this. Basically, what I'm doing is:
* filter paths by depth and HTTP method
* compare split paths arrays instead of recursive traversing
* if there are more matching paths, get the one with the smallest number of params
> Improve PathItemFinder

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validators/string_validator.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
- append the example (if present) to the error message when using a pattern validator on a string type
This makes the error messages for pattern validation much easier by giving the user an example they can key off of. 
Before:
`"#/paths/~1validate_test/post/requestBody/content/application~1json/schema/properties/number_str pattern [0-9]+:[0-9]+ does not match value: 11922`
After:
`"#/paths/~1validate_test/post/requestBody/content/application~1json/schema/properties/number_str pattern [0-9]+:[0-9]+ does not match value: 11922, example: 11:22"`
> Append the example to the Pattern validator error message

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validators/string_validator.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
The openapi spec supports strings with UUID format. This PR adds support for validating UUID strings using regular expression.
> Added support for validating UUID formatted strings

- openapi_parser.gemspec
I think we use pry in dev_dependency so we don't need drop ruby 2.3.0 support.
> freeze pry version because failed in ruby 2.3.0

- lib/openapi_parser.rb
- lib/openapi_parser/concerns/findable.rb
- lib/openapi_parser/schemas/openapi.rb
- spec/data/cyclic-remote-ref1.yaml
- spec/data/cyclic-remote-ref2.yaml
- spec/data/petstore.json
- spec/data/petstore.json.unsupported_extension
- spec/data/petstore.yaml.unsupported_extension
- spec/data/remote-file-ref.yaml
- spec/data/remote-http-ref.yaml
- spec/openapi_parser/concerns/findable_spec.rb
- spec/openapi_parser_spec.rb
- spec/spec_helper.rb
Reference to files in local filesystem and files provided via http(s)/ftp is supported.
Changes are as follows:
- `@uri` is added to `OpenAPIParser::Schemas::OpenAPI`
- It is used for resolving relative uri in $ref
- `@schema_registry` is added to `OpenAPIParser::Schemas::OpenAPI`
- It is used for preventing schema from being loaded multiple times
- New methods to load schema are added to `OpenAPIParser`
- The existing `#parse` method is not aware of schema content's location. I added new methods that also load files from filepath or uri, thus they can set uri for loaded schema.
I have following concerns.
- I did not put `@uri` and `@schema_registry` inside `config`, because I thought they do not fit into configuration. Interface would be simpler if I put them into config though.
- There …
> Support $ref to objects in other OpenAPI yaml files

- lib/openapi_parser/schemas/paths.rb
- spec/data/path-item-ref.yaml
- spec/openapi_parser/path_item_ref_spec.rb
- spec/spec_helper.rb
Path item object can have $ref, but currently it is not supported.
https://github.com/OAI/OpenAPI-Specification/blob/2d6a1809f3ee5c765a79db0ebc14bd2a03119c77/versions/3.0.2.md#path-item-object
> Allow $ref for path item objects

- lib/openapi_parser.rb
- spec/openapi_parser_spec.rb
[I found it difficult to use remote reference feature from committee 😞](https://github.com/kiyot/committee/commit/a8dec26134769eb9f7d05148bf7d698eb4fa6501#diff-e6155e253d47a7b2ed2bde066e07f3e1R53-R61)
So I added a new method that can be called from committee with ease.
Btw thank you for fixing #72 ❤️
> Add committee friendly interface to use remote references.

- lib/openapi_parser.rb
- spec/data/normal.yml
Add Date and Time to `Psych.safe_load`'s `permitted_classes`.
Using date or time in examples causes following error.
```
Psych::DisallowedClass:
Tried to load unspecified class: Time
```
> Allow date and time content in YAML

- lib/openapi_parser/path_item_finder.rb
`matching` in this context has the format of
```
['/user/{id}/edit', { 'id' => 1 }]
```
As the idea is to find matching path by minimum path params, the code should find min by the size of second element
> Find path by extracted params than path length, Close #75

- lib/openapi_parser/concerns/findable.rb
- spec/data/path-item-ref.yaml
I was having a similar issue to #77. I _think_ this may fix that issue, but I'm not 100% sure.
Given that OpenAPI expects `$ref` values to be RFC3986-compliant percent-encoded, this can cause issues with embedded refs that live on a path with a parameter. The percent-encoding throws off the path matching in `find_object`. This PR simply URI unescapes the `ref` before attempting the lookup, which fixes the issue. Existing tests cover this functionality, so only a minor tweak to `path-item-ref.yaml` was required to validate the desired behavior. 
Example:
```yaml
/sample/{sample_id}:
... snipped ...
/ref-sample:
$ref: '#/paths/~1sample~1%7Bsample_id%7D'
```
Also wanted to mention how much effort this library has saved me. Excellent work!
> Unescape ref URI before lookup in OpenAPIParser::Findable

- lib/openapi_parser/concerns/findable.rb
I got many obsolete warning messages after upgrade to v0.12.0.
```
.../vendor/bundle/ruby/2.7.0/gems/openapi_parser-0.12.0/lib/openapi_parser/concerns/findable.rb:7: warning: URI.unescape is obsolete
```
https://github.com/ruby/ruby/blob/master/lib/uri/common.rb#L132
> Use CGI.unescape

- lib/openapi_parser/concerns/findable.rb
- spec/data/remote-file-ref.yaml
Resolving remote reference to path items with path parameters causes URI::InvalidURIError.
Remote reference resolution creates URI from reference string. Path parameters uses '{' and '}', which are not usable in URI. So reference string needs to be kept escaped.
> Fix a problem with remote reference to path items which have path parameters

- lib/openapi_parser/path_item_finder.rb
fix typo on comments for method
`mathing` -> `matching`
> fix typo: mathing -> matching

- lib/openapi_parser/errors.rb
- spec/openapi_parser/request_operation_spec.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
- spec/openapi_parser/schema_validator_spec.rb
- spec/spec_helper.rb
This PR makes it easier to pursue the cause when unexpected values appear.
For example, when empty string is included in enum.
`isn't include enum`
`"" isn't include enum`
> Use inspect to show error value

- lib/openapi_parser/errors.rb
- spec/openapi_parser/schema_validator_spec.rb
It updates the error message for enums from
"{value} isn't include enum in {reference}"
to
"{value} isn't part of the enum in {reference}"
> Updates error message for enums to be more readable

- lib/openapi_parser/schema_validators/boolean_validator.rb
- spec/data/normal.yml
- spec/openapi_parser/schema_validator_spec.rb
If my reading of the spec is correct, `enum` should be supported for all data types, including booleans.
In our case, we are trying to specify that a boolean must have a specific value when constraining with a set of `oneOf` schemas. For example:
```
ControlledDigitalLendingAccess:
type: object
properties:
access:
description: Access level.
type: string
enum:
- stanford
download:
description: Download access level.
type: string
enum:
- none
readLocation:
description: If access is "location-based", which location should have access.
type: string
nullable: true
enum:
- null
controlledDigitalLending:
description: Available for controlled digital lending.
type: boolean
required:
- access
- download
- controlledDigitalLending
StanfordAccess:
type: object
properties:
access:
description: Access …
```
> Support enum for booleans.

- lib/openapi_parser/schema_validators/all_of_validator.rb
- lib/openapi_parser/schema_validators/base.rb
- lib/openapi_parser/schema_validators/object_validator.rb
- spec/data/petstore-with-mapped-polymorphism.yaml
- spec/data/petstore-with-polymorphism.yaml
- spec/openapi_parser/schemas/polymorphism_spec.rb
- spec/spec_helper.rb
This adds support for `discriminator` use without `oneOf` as described in the spec as [models with polymorphism support](http://spec.openapis.org/oas/v3.0.3#models-with-polymorphism-support). Hope I didn't create too much of a mess.
> Add basic polymorphism handling

- lib/openapi_parser/schema_validator.rb
- lib/openapi_parser/schema_validators/unspecified_type_validator.rb
- spec/data/normal.yml
- spec/openapi_parser/schema_validator_spec.rb
The OpenAPI 3.0 spec (and the JSON schema spec it derives from) states that a schema without a type matches any data type, and that empty schemas are valid. This changes the parser to follow the spec.
See https://swagger.io/docs/specification/data-models/data-types/#any and https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-4.3.2
An alternative implementation here would be to treat an empty schema like an `anyOf` over all primitive types as the swagger.io page suggests. However, in that case we'd still need to support empty schema for the `array` and `object` possibilities within the `anyOf`, so the implementation in this PR seems more straightforward.
> Support empty schema as any type

- lib/openapi_parser/schema_validators/float_validator.rb
- lib/openapi_parser/schema_validators/integer_validator.rb
- spec/data/normal.yml
- spec/openapi_parser/schema_validator_spec.rb
Found that attempting to coerce a non-string type (eg. boolean) to a float or integer caused a TypeError rather than an ArgumentError. This meant that `anyOf` had to be crafted so that numeric types were last to prevent a possible crash in certain situations.
This PR rescues the `TypeError` and causes the validator to behave as expected when the value cannot be coerced.
> Fix anyOf coercion to float and integer when value is a non-string type

- TAGS
- lib/openapi_parser/concerns/findable.rb
- spec/data/path-item-ref-relative.yaml
- spec/data/path-item-ref.yaml
- spec/openapi_parser/path_item_ref_spec.rb
- spec/spec_helper.rb
Path reference of other file cannot parse by json pointer escape (ex. '/' -> '~1' ).
We need to separate each path file for large open-api document.
example yaml file:
```yaml
openapi: 3.0.0
info:
version: 1.0.0
title: OpenAPI3 Sample
paths:
/ref-sample/relative:
$ref: 'Pets.yaml#/paths/~1pets~1owners'
openapi: 3.0.0
info:
version: 1.0.0
title: OpenAPI3 Sample
paths:
/pets/owners:
...
```
error message:
```shell
URI::InvalidURIError:
bad URI(is not URI?): "Pets.yml#/paths/~1pets~1owners"
```
> support: relative file path escape.

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validators/string_validator.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
- spec/openapi_parser/schema_validator_spec.rb
Add date-time format validation.
This change does not change the behavior of the datetime_coerce_class option on success.
However, the exception class for failures has changed.
Refs.
- http://spec.openapis.org/oas/v3.0.3#data-types
- https://tools.ietf.org/html/rfc3339#section-5.6
- https://docs.ruby-lang.org/ja/latest/method/Time/s/iso8601.html
> Add date-time format validation

- lib/openapi_parser/schema_validators/unspecified_type_validator.rb
- spec/openapi_parser/schema_validator_spec.rb
Need to wrap value with array otherwise return value of `#validate_schema`
is assigned to `err` if `value` is an array.
> Fix TypeError when array is passed to UnspecifiedTypeValidator

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validator/array_validator.rb
- spec/openapi_parser/schema_validator/array_validator_spec.rb
Hi @ota42y,
I have added validation of the uniqueness of items in array.
This enables us to raise errors in arrays like `[1, 1, 3]`.
```
type: array
items:
type: integer
uniqueItems: true
```
https://swagger.io/docs/specification/data-models/data-types/
> Support for uniqueItems in array

- lib/openapi_parser/schema_validator/all_of_validator.rb
- lib/openapi_parser/schema_validator/any_of_validator.rb
- lib/openapi_parser/schema_validator/one_of_validator.rb
- spec/data/normal.yml
- spec/openapi_parser/schema_validator_spec.rb
This PR fixes validation error when null value is passed on `allOf`, `anyOf` and `oneOf` schemas with `nullable: true`.
Note: Instead of #125, `nullable` is used in `oneOf` schema itself.
> Fix nullable field does not work with allOf, anyOf and oneOf keyword

- .github/workflows/ci.yaml
- CHANGELOG.md
- Rakefile
- lib/openapi_parser/version.rb
- openapi_parser.gemspec
error occured
```
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use 
`gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid
future breakage and silence this warning by running `gem update --system 3.2.3`
```
> drop ruby 2.6

- lib/openapi_parser/schema_validator/all_of_validator.rb
- lib/openapi_parser/schema_validator/object_validator.rb
- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schema_validator/all_of_validator_spec.rb
For now, when passing schemas like : 
```yml
type: object
required:
- head_count
properties:
head_count:
type: integer
format: int64
mass:
type: integer
additionalProperties:
type: string  
```
there is no error triggered on value like : 
```ruby
{
"color"       => "gold",
"head_count" => 20,
"speed"      => 20
}
```
because the gem does not support validating schemas inside `additionalProperties` field. This PR intends to support this behaviour.
While implementing this PR, some specs in `all_of_validator_spec` were failing (or not failing) because of some combination of subschemas in allOf having `additionalProperties` to false. But according to [OpenApi specification](https://spec.openapis.org/oas/latest.html), "allOf takes an array of object definitions that are validated independently …
> support schemas validation in additionalProperties + remove additionalProperties logic from allof

- lib/openapi_parser/schemas/schema.rb
This code emits the following warning to anyone who uses the gem, unless they suppress it with something like the warning gem, or suppress all warnings:
3.2.4/lib/ruby/gems/3.2.0/gems/openapi_parser-2.1.0/lib/openapi_parser/schemas/schema.rb:113: warning: method redefined; discarding old additional_properties
This has been the case for about five years, although the comments make reference to this situation being transitory.  It would be better to use the gem without it emitting warnings in the meantime.
> Suppress "method redefined" warning

- openapi_parser.gemspec
For example, see: https://github.com/ota42y/openapi_parser/actions/runs/11315396259
> add base64 devdep for ruby-head, as steep needs but doesn't explicitly require it

- lib/openapi_parser.rb
- lib/openapi_parser/schema_validator/string_validator.rb
- spec/openapi_parser/request_operation_spec.rb
- spec/openapi_parser/schema_validator_spec.rb
Now that we support Ruby 2.7 and above, we can remove conditions with versions lower than that.
> Remove unused codes

- lib/openapi_parser/schema_validator/string_validator.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
Quoting from the JSON schema validation vocabulary
> date:  A string instance is valid against this attribute if it is a
>        valid representation according to the "full-date" production.
and from RFC 3339
```
date-fullyear   = 4DIGIT
date-month      = 2DIGIT  ; 01-12
date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
; month/year
full-date       = date-fullyear "-" date-month "-" date-mday
```
The current implementations allows date strings that don't comply, for
example `"12-12-12"`. The regex based check fixes that.
References:
* OAS 3.0.0 https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#dataTypes
* JSON validation vocabulary https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-7.3
* RFC 3339, section 5.6 …
> fix date string format validation

- lib/openapi_parser/errors.rb
- lib/openapi_parser/schema_validator.rb
- lib/openapi_parser/schema_validator/object_validator.rb
- lib/openapi_parser/schema_validator/properties_number.rb
- spec/openapi_parser/schema_validator/object_validator_spec.rb
https://swagger.io/docs/specification/data-models/data-types/
> The minProperties and maxProperties keywords let you restrict the number of properties allowed in an object. This can be useful when using additionalProperties or free-form objects.
> Support maxProperties and minProperties

- lib/openapi_parser/request_operation.rb
- spec/openapi_parser/request_operation_spec.rb
The content_type method looks up the content type header in a case sensitive manner; this causes a validation error [here](https://github.com/ota42y/openapi_parser/blob/b88556b38f54a5cf59b27399b9a29333c34b859d/lib/openapi_parser/schemas/response.rb#L22-L25) when the response headers aren't sent in exactly as `Content-Type` and strict validation is enabled. 
This pull request makes the content_type method case insensitive.
> Make content_type case insensitive

- lib/openapi_parser/schema_validator/string_validator.rb
- spec/openapi_parser/schema_validator/string_validator_spec.rb
Ref #148
The motivation of this patch comes from https://github.com/interagent/committee/issues/255.
> Skip validation if the format is `binary`, even if the value is not an actual string.

- lib/openapi_parser/config.rb
- lib/openapi_parser/schema_validator.rb
- lib/openapi_parser/schema_validator/options.rb
- lib/openapi_parser/schema_validator/string_validator.rb
- sig/openapi_parser/config.rbs
- sig/openapi_parser/schema_validators/options.rbs
- spec/openapi_parser/schema_validator/string_validator_spec.rb
This is the last patch from our recent update from Committee 4.4 to 5.
It seems empty string is considered valid for date/date-time from the spec, but I feel it's kind of grey area.
This change could also be backwards incompatible, so I'm open to suggestions on how to add an option or something. It wasn't obvious to me how we can pass options from Committee (we're mainly using for `assert_schema_conform` in our tests).
Here is the investigation from my colleague (@ydah) which I think adds a bit more context:
---
This is the most common testing pattern that this update has caused to fail.
The following changes to openapi_parser add date and date-time validation:
* https://github.com/ota42y/openapi_parser/pull/102
* https://github.com/ota42y/openapi_parser/pull/126
In the above fix, the …
> Allow empty date/date-time to pass validation

- lib/openapi_parser/schema_validator/options.rb
- lib/openapi_parser/schemas/response.rb
- spec/openapi_parser/schemas/responses_spec.rb
We need to be able to pass options to the validator when parsing responses too.
> Support validator options on ResponseValidateOptions

- lib/openapi_parser/schema_validator/all_of_validator.rb
- lib/openapi_parser/schema_validator/object_validator.rb
- spec/data/petstore-with-discriminator.yaml
- spec/openapi_parser/schema_validator/all_of_validator_spec.rb
- spec/openapi_parser/schema_validator/object_validator_spec.rb
- add tests for additional properties scenarios and Rabbit schema
- add validations for typed additional properties
- still skips additional properties validation in allOf (for now anyway)
closes #186
> feat(schema-validator): enhance additional properties validation
